FROM mysql:8.0

# Configurar variables de entorno
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=rionegro_demo
ENV MYSQL_USER=rionegro_user
ENV MYSQL_PASSWORD=userpassword

# Copiar el archivo de inicialización
COPY init.sql /docker-entrypoint-initdb.d/

# Exponer el puerto
EXPOSE 3306
